import { Inter } from "next/font/google";
import "./globals.css";
import Lenis from "../components/Lenis";
import Footer from "../components/Footer";
import Header from "../components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Healers Healthcare",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Lenis>
          <Header />
          <main className="max-w-7xl mx-auto xl:px-0 md:px-8 px-6 lg:py-0 py-6">
            {children}
          </main>
          <Footer />
        </Lenis>
      </body>
    </html>
  );
}
